### ISSUE TITLE
运行缺失dll

### ISSUE THREAD

**Issue by laixuechaochn** [srymurphy/ffmpeg2webrtc#1]
运行ffmpeg2webrtc.exe报缺失zlib1.dll、libbz2-1.dll、liblzma-5.dll、libiconv-2.dll，下载这些dll后运行报错无法正常启动（0xc000007b）。能不能提供一个简单的使用手册，谢谢

**Comment by srymurphy** [comment]
我用的msys2 64位编译的   你可能下的事32位版本，我在发布包中更新了依赖库，需要的话可以下载试试
